name: 'Sample composite action'
description: 'This is something we could do as a demo'
inputs:
  project:  # id of input
    description: 'name of a project'
    required: true
    default: 'anyProject'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo The project is called ${{ inputs.project }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - run: myScript.sh
      shell: bash
